# Lakehouse 配置示例

# 服务监听配置
server:
  port: 22331  # 监听端口号
  host: 0.0.0.0
  workers: 4

# 数据湖存储路径配置
storage:
  data_lake_path: "/mnt/data/Lake_Data"  # 数据湖存储路径

# 数据处理配置
convert:
  workers: 6  # 并行处理线程数

# 数据库连接配置
database:
  # SQL 数据库连接信息
  sql:
    SQLAlchemy_path: "mysql+pymysql://root:cetc15s@192.168.10.58:3306/lakehouse_db"  # 数据库类型，例如: postgresql, mysql, sqlite等

  # Qdrant 数据库连接信息
  qdrant:
    host: "192.168.10.58"   # Qdrant服务地址
    port: 6333          # Qdrant服务端口
    collection: "your_collection_name"  # Qdrant集合名称

# 数据集导出配置
export:
  base_path: "/mnt/data/Lake_Data"  # 数据集导出的主路径
  input_base_path: "/mnt/data/ML_folder/Data_KJ"  # 存储统一转换成json文件的主路径
  md_base_path: "/mnt/data/ML_folder/Data_KJ_md"  # 中间md文件的主路径



# 文本向量化API服务配置
text_vectorization:
  api_url: "http://localhost:5000"  # 文本向量化服务的URL
  api_key: "your_api_key_here"  # 如有需要，提供API密钥
  truncation_length: 4096  # 文本截断长度
